TRAIN:
  ENABLE: True
  DATASET: kinetics
  BATCH_SIZE: 64
  EVAL_PERIOD: 5
  CHECKPOINT_PERIOD: 5
  AUTO_RESUME: True
DATA:
  USE_OFFSET_SAMPLING: True 
  DECODING_BACKEND: torchvision
  NUM_FRAMES: 8
  SAMPLING_RATE: 16
  TRAIN_JITTER_SCALES: [224, 256]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 224
  INPUT_CHANNEL_NUM: [3]
  MEAN: [0.48145466, 0.4578275, 0.40821073]
  STD: [0.26862954, 0.26130258, 0.27577711]
AUG:
  NUM_SAMPLE: 2
  ENABLE: False
  COLOR_JITTER: 0.4
  AA_TYPE: rand-m7-n4-mstd0.5-inc1
  INTERPOLATION: bicubic
  RE_PROB: 0.25
  RE_MODE: pixel
  RE_COUNT: 1
  RE_SPLIT: False
BN:
  USE_PRECISE_STATS: False
  NUM_BATCHES_PRECISE: 200
SOLVER:
  ZERO_WD_1D_PARAM: True
  CLIP_GRAD_L2NORM: 1.0
  BASE_LR_SCALE_NUM_SHARDS: True
  BASE_LR: 1e-5
  COSINE_AFTER_WARMUP: True
  COSINE_END_LR: 1e-7
  WARMUP_START_LR: 1e-7
  WARMUP_EPOCHS: 1.0
  LR_POLICY: cosine
  MAX_EPOCH: 12
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.01
  OPTIMIZING_METHOD: adamw
MODEL:
  NUM_CLASSES: 400
  ARCH: vitb16
  MODEL_NAME: TemporalClipVideo
  LOSS_FUNC: cross_entropy
  DROPOUT_RATE: 0.5
  TEMPORAL_MODELING_TYPE: expand_temporal_view
TEST:
  ENABLE: True
  DATASET: kinetics
  BATCH_SIZE: 64
  NUM_SPATIAL_CROPS: 1
  NUM_ENSEMBLE_VIEWS: 3
DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: True
NUM_GPUS: 8
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: .
